#!/bin/bash
# Script para eliminar tablas del servidor remoto CLINICA_FINAL

# Nota: Este script requiere que sqlplus esté instalado localmente
# o que tengas acceso SSH al servidor 4.156.223.214

echo "Por favor ejecuta este script en el servidor 4.156.223.214"
echo "O conéctate por SSH y ejecuta:"
echo ""
echo "sqlplus CLINICA/1234@localhost:1521/XEPDB1 <<'EOSQL'"
echo "SET SERVEROUTPUT ON SIZE UNLIMITED"
echo ""
echo "-- Matar todas las sesiones del usuario CLINICA excepto la actual"
echo "DECLARE"
echo "  v_current_sid NUMBER;"
echo "BEGIN"
echo "  SELECT sid INTO v_current_sid FROM v\\\$mystat WHERE rownum = 1;"
echo "  "
echo "  FOR rec IN ("
echo "    SELECT sid, serial# "
echo "    FROM v\\\$session "
echo "    WHERE username = 'CLINICA'"
echo "      AND sid != v_current_sid"
echo "  ) LOOP"
echo "    EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || rec.sid || ',' || rec.serial# || ''' IMMEDIATE';"
echo "    DBMS_OUTPUT.PUT_LINE('Sesión eliminada: ' || rec.sid);"
echo "  END LOOP;"
echo "END;"
echo "/"
echo ""
echo "-- Esperar que las sesiones mueran"
echo "EXEC DBMS_LOCK.SLEEP(3);"
echo ""
echo "-- Eliminar todas las tablas"
echo "BEGIN"
echo "  FOR rec IN (SELECT table_name FROM user_tables ORDER BY table_name) LOOP"
echo "    BEGIN"
echo "      EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS PURGE';"
echo "      DBMS_OUTPUT.PUT_LINE('✓ ' || rec.table_name);"
echo "    EXCEPTION"
echo "      WHEN OTHERS THEN"
echo "        DBMS_OUTPUT.PUT_LINE('✗ ' || rec.table_name || ': ' || SQLERRM);"
echo "    END;"
echo "  END LOOP;"
echo "END;"
echo "/"
echo ""
echo "-- Verificar"
echo "SELECT COUNT(*) as TABLAS_RESTANTES FROM user_tables;"
echo ""
echo "EXIT;"
echo "EOSQL"
